#!/usr/bin/env python3
"""Write dist/_redirects (Cloudflare Pages) and dist/links.csv.

  /r/<code> <final URL> 302

Page numbers come from the \\zlabel{link:<code>} of every QR code in the
final .aux files.  Statuses come from links/url_status.json
(tools/check_links.py); a URL that was never checked is "unchecked".
"""
import csv
import json
import os
import re
from urllib.parse import quote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def pages():
    out = {}
    for v in range(1, 7):
        aux = os.path.join(ROOT, 'build', 'tex', 'vol%d.aux' % v)
        if not os.path.exists(aux):
            continue
        for m in re.finditer(r'\\zref@newlabel\{link:([^}]+)\}\{(.*)',
                             open(aux, encoding='utf-8').read()):
            p = re.search(r'\\page\{([^}]*)\}', m.group(2))
            if p:
                out.setdefault(m.group(1), p.group(1))
    return out


def safe(url):
    # no spaces or other characters that would break a _redirects line
    return quote(url, safe=":/?#[]@!$&'()*+,;=%~-._")


def code_key(code):
    v, n = code.split('-')
    return (int(v), n.startswith('c'), int(n.lstrip('c')))


def main():
    reg = json.load(open(os.path.join(ROOT, 'build', 'links_registry.json'),
                         encoding='utf-8'))['links']
    disc = json.load(open(os.path.join(ROOT, 'build', 'discussions.json'),
                          encoding='utf-8'))
    status = {}
    p = os.path.join(ROOT, 'links', 'url_status.json')
    if os.path.exists(p):
        status = json.load(open(p, encoding='utf-8'))
    pg = pages()
    rows = []
    for l in reg:
        st = status.get(l['url'], {})
        rows.append({'code': l['code'], 'volume': l['vol'],
                     'page': pg.get(l['code'], ''),
                     'link text': l['text'],
                     'original URL': l['url'],
                     'final URL': st.get('final', l['url']),
                     'status': st.get('status', 'unchecked'),
                     'kind': {'url': 'url in text', 'ext': 'ebook link',
                              'exturl': 'ebook link'}[l['kind']]
                     + {'footnote': ' (footnote)', 'body': ' (text)',
                        'bib': ' (bibliography)'}[l['where']]})
    for code, d in disc.items():
        st = status.get(d['url'], {})
        rows.append({'code': code, 'volume': d['vol'],
                     'page': pg.get(code, ''),
                     'link text': 'Discussion: ' + d['title'],
                     'original URL': d['url'],
                     'final URL': st.get('final', d['url']),
                     'status': st.get('status', 'unchecked'),
                     'kind': 'discussion (LessWrong comments)'})
    rows.sort(key=lambda r: code_key(r['code']))
    os.makedirs(os.path.join(ROOT, 'dist'), exist_ok=True)
    with open(os.path.join(ROOT, 'dist', 'links.csv'), 'w', newline='',
              encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=['code', 'volume', 'page',
                                          'link text', 'original URL',
                                          'final URL', 'status', 'kind'])
        w.writeheader()
        w.writerows(rows)
    with open(os.path.join(ROOT, 'dist', '_redirects'), 'w',
              encoding='utf-8') as f:
        f.write('# Short links of the print edition of "Rationality: From AI'
                ' to Zombies".\n# Cloudflare Pages format; generated by'
                ' tools/redirects.py, see links.csv.\n')
        for r in rows:
            f.write('/r/%s %s 302\n' % (r['code'], safe(r['final URL'])))
    missing = [r['code'] for r in rows if not r['page']]
    print('links.csv: %d rows; %d without page number%s'
          % (len(rows), len(missing), (': ' + ' '.join(missing[:20])) if missing else ''))


if __name__ == '__main__':
    main()
